### ISSUE TITLE
Add support to "vector_dims" when using sqlalchemy ORM

### ISSUE THREAD

**Issue by ostefano** [pgvector/pgvector-python#53]
See https://github.com/pgvector/pgvector/issues/426 otherwise it is not possible to use `pgvector-python` with `sqlalchemy-orm` and tables containing vectors with multiple dimensions.

**Comment by ostefano** [comment]
A workaround (which might be enough) seems to be adding a clause using `where(text("vector_dims(field) = ${vector_len of the queried term}"))`

**Comment by ankane** [comment]
Hi @ostefano, thanks for the suggestion. Can you share more details about the specific use case? Typically, vectors with different dimensions will come from different models, so you'll want another field like `model_id` on the table to use for filtering instead (since even if two models have the same number of dimensions, you don't want to compare embeddings across models).

**Comment by ostefano** [comment]
Hi @ankane indeed you are right, that shall not be needed. However it is counterintuitive from a DB perspective that the select would stop working, and there is not much documentation about it. Happy to close it, but I would mention this aspect more prominently.
